blank_issues_enabled: false
contact_links:
  - name: Link apps to identical icons
    url: https://github.com/k4ustu3h/forkicons/blob/main/CONTRIBUTING.md#adding-an-icon-to-forkicons
    about: Learn more about linking an app to an existing icon via a pull request.
