blank_issues_enabled: false
contact_links:
  - name: Link apps and icons
    url: https://github.com/k4ustu3h/forkicons/blob/main/CONTRIBUTING.md#adding-icons-and-missing-app-components-to-forkicons
    about: Learn more about linking an app to an existing icon via a pull request.
