name: Report outdated icons
description: Request changing an icon if its design is outdated.
labels: ["icon design"]
body:
  - type: textarea
    id: outdated-icon-list
    attributes:
      label: Icons
      description: |
        **Before you start**
        Please note that we only consider icon design changes. If it remains the same, you will probably find it useful to know [how to link apps and icons](https://github.com/k4ustu3h/forkicons/blob/main/CONTRIBUTING.md#adding-icons-and-missing-app-components-to-forkicons).

        **How to find the current icon and app name**
        You can find the current icon and app name in the Forkicons app. Also, you can search the [appfilter.xml](https://github.com/k4ustu3h/forkicons/blob/main/app/assets/appfilter.xml). For instance, you found "...**drawable="ladb" name="ADB Shell" />**". The icon is [ladb](https://github.com/k4ustu3h/forkicons/tree/main/svgs/ladb.svg) and the app name is **ADB Shell**.

        **Sample response**
        X (formerly Twitter)
        Now: https://github.com/k4ustu3h/forkicons/tree/main/svgs/x.svg
        New: https://cdn.cms-twdigitalassets.com/content/dam/about-twitter/x/brand-toolkit/logo-black.png.twimg.2560.png

      placeholder: Tell us about outdated and new icons
    validations:
      required: true
