name: first-interaction

on:
  pull_request:
    branches: [develop]
    types: [opened]
    paths:
      - "**.svg"
      - "!app/src/**"
      - "!**.gradle.kts"

jobs:
  check_pr:
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - name: Send message if first interaction
        if: steps.outcome != 'failure'
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pr-message: |
            Thanks for your interest in contributing to Forkicons!
            Ensure that the icons match the [Forkicons guidelines](https://github.com/k4ustu3h/forkicons/blob/develop/.github/CONTRIBUTING.md#icon-guidelines).
            If something is wrong with your icons, please correct them and update the PR.
            If everything is according to the guidelines, the reviewers will quickly accept the PR. Otherwise, you will be asked to fix the icons.
